# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_city_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zip_code',
            field=models.CharField(default='test', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
