# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20170410_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(max_length=25),
        ),
    ]
